#define RULE_TOKEN_TERMINATION                      1
#define RULE_TOKEN_UNINITIALIZED                    2
#define RULE_TOKEN_KEYWORD_ALLOW                    3
#define RULE_TOKEN_KEYWORD_DENY                     4
#define RULE_TOKEN_KEYWORD_REJECT                   5
#define RULE_TOKEN_HEXCHAR4                         6
#define RULE_TOKEN_COLON                            7
#define RULE_TOKEN_ASTERISK                         8
#define RULE_TOKEN_KEYWORD_CLASS                    9
#define RULE_TOKEN_KEYWORD_HASH                    10
#define RULE_TOKEN_KEYWORD_NAME                    11
#define RULE_TOKEN_KEYWORD_PORT                    12
#define RULE_TOKEN_CURLYBRACE_OPEN                 13
#define RULE_TOKEN_CURLYBRACE_CLOSE                14
#define RULE_TOKEN_KEYWORD_ACTION                  15
#define RULE_TOKEN_DQ_STRING_BEGIN                 16
#define RULE_TOKEN_DQ_STRING                       17
#define RULE_TOKEN_DQ_STRING_END                   18
