#define CLI_TOKEN_TERMINATION                      1
#define CLI_TOKEN_UNINITIALIZED                    2
#define CLI_TOKEN_KEYWORD_RULE                     3
#define CLI_TOKEN_KEYWORD_DEVICE                   4
#define CLI_TOKEN_KEYWORD_APPEND                   5
#define CLI_TOKEN_OPTION_PARENT                    6
#define CLI_TOKEN_OPTION_TIMEOUT                   7
#define CLI_TOKEN_OPTION_PERMANENT                 8
#define CLI_TOKEN_KEYWORD_REMOVE                   9
#define CLI_TOKEN_KEYWORD_LIST                    10
#define CLI_TOKEN_KEYWORD_HASH                    11
#define CLI_TOKEN_KEYWORD_SET_POLICY              12
#define CLI_TOKEN_NUMBER_UNSIGNED_INTEGER         13
#define CLI_TOKEN_KEYWORD_LAST                    14
#define CLI_TOKEN_KEYWORD_ROOT                    15
#define CLI_TOKEN_NUMBER_HOURS                    16
#define CLI_TOKEN_NUMBER_MINUTES                  17
#define CLI_TOKEN_NUMBER_DAYS                     18
#define CLI_TOKEN_KEYWORD_FALSE                   19
#define CLI_TOKEN_KEYWORD_TRUE                    20
#define CLI_TOKEN_STRING                          21
#define CLI_TOKEN_DQ_STRING_BEGIN                 22
#define CLI_TOKEN_DQ_STRING_END                   23
