.\" Generated with Ronnjs 0.4.0
.\" http://github.com/kapouer/ronnjs
.
.TH "USBGUARD\-DAEMON" "8" "April 2015" "" "8"
.
.SH "NAME"
\fBusbguard-daemon\fR \-\- A tool for implementing USB device usage policy
.
.SH "SYNOPSIS"
\fBusbguard\-daemon\fR [<options>]
.
.SH "DESCRIPTION"
The USBGuard software framework helps to protect your computer against rogue USB devices (a\.k\.a\. BadUSB) by implementing basic whitelisting/blacklisting capabilities based on USB device attributes\.
.
.SH "OPTIONS"
.
.IP "\(bu" 4
\fB\-d\fR
Enable debugging messages in the log\.
.
.IP "\(bu" 4
\fB\-s\fR
Log to syslog\.
.
.IP "\(bu" 4
\fB\-k\fR
Log to console\.
.
.IP "\(bu" 4
\fB\-l <path>\fR
Log to a file at \fIpath\fR\|\.
.
.IP "\(bu" 4
\fB\-p <path>\fR
Write PID to a file at \fIpath\fR\|\.
.
.IP "\(bu" 4
\fB\-c <path>\fR
Load configuration from a file at \fIpath\fR (default: \fI/etc/usbguard/usbguard\-daemon\.conf\fR)\.
.
.IP "\(bu" 4
\fB\-h\fR
Show the help/usage screen\.
.
.IP "" 0
.
.SH "SECURITY CONSIDERATIONS"
The daemon provides the USBGuard public IPC interface\. Depending on your distribution defaults, the access to this interface is limited to a certain group or a specific user only\. Please refer to the usbguard\-daemon\.conf(5) man\-page for more information on how to configure the ACL correctly\. \fIDo not leave the ACL unconfigured as that will expose the IPC interface to all local users and will allow them to manipulate the authorization state of USB devices and modify the USBGuard policy\fR\|\.
.
.SH "BUGS"
If you find a bug in this software or if you\'d like to request a feature to be implemented, please file a ticket at https://github\.com/dkopecek/usbguard/issues/new \fI\fR\|\.
.
.SH "AUTHOR"
Daniel Kopeček \fIdkopecek@redhat\.com\fR
.
.SH "COPYRIGHT"
Copyright © 2015 Red Hat, Inc\.  License GPLv2+: GNU GPL version 2 or later \fIhttp://gnu\.org/licenses/gpl\.html\fR\|\. This is free software: you are free to change and redistribute it\.  There is NO WARRANTY, to the extent permitted by law\.
.
.SH "SEE ALSO"
usbguard\-daemon\.conf(5), usbguard\-applet\-qt(1)