.TH "USBGUARD\-APPLET\-QT" "1" "June 2016" "" ""
.SH NAME
.PP
\f[B]usbguard\-applet\-qt\f[] \-\- USBGuard Qt applet
.SH SYNOPSIS
.PP
\f[B]usbguard\-applet\-qt\f[]
.SH DESCRIPTION
.PP
USBGuard Qt applet for interaction with the USBGuard daemon.
.SH OPTIONS
.PP
There are currently no options available.
.SH SECURITY CONSIDERATIONS
.PP
The applet uses the USBGuard public IPC interface to talk to the daemon
component.
Depending on your distribution defaults, the access to this interface is
limited to a certain group or a specific user only.
Please refer to the \f[B]usbguard\-daemon.conf\f[](5) man page for more
information on how to configure the ACL correctly.
Do not leave the ACL unconfigured as that will expose the IPC interface
to all local users and will allow them to manipulate the authorization
state of USB devices and modify the USBGuard policy.
.SH BUGS
.PP
If you find a bug in this software or if you\[aq]d like to request a
feature to be implemented, please file a ticket at
<https://github.com/dkopecek/usbguard/issues/new>.
.SH COPYRIGHT
.PP
Copyright © 2015 Red Hat, Inc.
License GPLv2+: GNU GPL version 2 or later
<http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH SEE ALSO
.PP
\f[B]usbguard\-daemon\f[](8), \f[B]usbguard\-daemon.conf\f[](5)
.SH AUTHORS
Daniel Kopeček <dkopecek@redhat.com>.
